#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using the private
# key ~/.ssh/school with the user ubuntu
ssh ubuntu@100.25.163.36 -i /alx-system_engineering-devops/0x0B-ssh/school
